spring:
  cloud:
    nacos:
      serverAddr: 192.168.2.23:8848
      # 以下配置项必须填写
      username: 'nacos'
      password: 'nacos'
  config:
    import:
      - nacos:nacos-config-example.properties?refreshEnabled=true&group=DEFAULT_GROUP